#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TimeKeeper.Models.SQLite;

namespace TimeKeeper.Models.SQLite	
{
	[NamingSettings(SourceStrategy = NamingSourceStrategy.Property, RemoveLeadingUnderscores = true, ResolveReservedWords = true, UseDelimitedSQL = true, WordBreak = "_")]
	public partial class Activity : OpenAccessContext, IActivityUnitOfWork
	{
		private static string connectionStringName = @"";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = AttributesMetadataSource.FromContext(typeof(Activity));
		
		public Activity()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public Activity(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public Activity(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public Activity(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public Activity(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<ActivityModel> ActivityModels 
		{
			get
			{
				return this.GetAll<ActivityModel>();
			}
		}
		
		public IQueryable<EntryModel> EntryModels 
		{
			get
			{
				return this.GetAll<EntryModel>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "SQLite";
			backend.ProviderName = "System.Data.SQLite";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of Activity.
		/// </summary>
		/// <param name="config">The BackendConfiguration of Activity.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IActivityUnitOfWork : IUnitOfWork
	{
		IQueryable<ActivityModel> ActivityModels
		{
			get;
		}
		IQueryable<EntryModel> EntryModels
		{
			get;
		}
	}
}
#pragma warning restore 1591
